import Dialog from '@/components/forms/Dialog';

import classes from './index.module.scss';

interface IPrivatePolicyDialogProps {
  open: boolean;
  onClose: () => void;
}

function PrivatePolicy() {
  return (
    <div className={classes.content}>
      <div>
        <p>1. Introduction</p>
        <div>
          <p>
            Welcome to Ditmar Hoxha, trading as Harmony. Ditmar Hoxha, trading
            as Harmony ("us", "we", or "our") , operates{' '}
            <a href="https://harmonyapp.ai" target="_blank">
              https://harmonyapp.ai/
            </a>
            (hereinafter referred to as "Service"). Our Privacy Policy governs
            your visit to{' '}
            <a href="https://harmonyapp.ai/" target="_blank">
              https://harmonyapp.ai/
            </a>
            , and explains how we collect, safeguard and disclose information
            that results from your use of our Service.{' '}
          </p>
          <p>
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions.
          </p>
          <p>
            Our Terms and Conditions ("<span>Terms</span>") govern all use of
            our Service and together with the Privacy Policy constitutes your
            agreement with us ("<span>agreement</span>").
          </p>
        </div>
      </div>
      <div>
        <p>2. Definitions</p>
        <div>
          <p>
            <span>SERVICE</span> means the{' '}
            <a href="https://harmonyapp.ai/" target="_blank">
              https://harmonyapp.ai/
            </a>{' '}
            website operated by Ditmar Hoxha, trading as Harmony
          </p>
          <p>
            <span>PERSONAL DATA</span> means data about a living individual who
            can be identified from those data (or from those and other
            information either in our possession or likely to come into our
            possession).
          </p>
          <p>
            <span>USAGE DATA</span> is data collected automatically either
            generated by the use of Service or from Service infrastructure
            itself (for example, the duration of a page visit).
          </p>
          <p>
            <span>COOKIES</span> are small files stored on your device (computer
            or mobile device).
          </p>
          <p>
            <span>DATA CONTROLLER</span> means a natural or legal person who
            (either alone or jointly or in common with other persons) determines
            the purposes for which and the manner in which any personal data
            are, or are to be, processed. For the purpose of this Privacy
            Policy, we are a Data Controller of your data.
          </p>
          <p>
            <span>DATA PROCESSORS</span> (<span>OR SERVICE PROVIDERS</span>)
            means any natural or legal person who processes the data on behalf
            of the Data Controller. We may use the services of various Service
            Providers in order to process your data more effectively.
          </p>
          <p>
            <span>DATA SUBJECT</span> is any living individual who is the
            subject of Personal Data.
          </p>
          <p>
            <span>THE USER</span> is the individual using our Service. The User
            corresponds to the Data Subject, who is the subject of Personal
            Data.
          </p>
        </div>
      </div>
      <div>
        <p>3. Information Collection and Use</p>
        <div>
          <p>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
        </div>
      </div>
      <div>
        <p>4. Types of Data Collected</p>
        <div>
          <div>
            <span>Personal Data</span>
            <div>
              <p>
                While using our Service, we may ask you to provide us with
                certain personally identifiable information that can be used to
                contact or identify you ("<span>Personal Data</span>").
                Personally identifiable information may include, but is not
                limited to:
              </p>
            </div>
          </div>
          <div>
            <div>
              <p>(a) Email address</p>
              <p>(b) First name and last name</p>
              <p>(c) Phone number</p>
              <p>(d) Address, State, Province, ZIP/Postal code, City</p>
              <p>(e) Cookies and Usage Data</p>
              <p>(f) Biometric data (facial assessments, photos, and others)</p>
            </div>
          </div>
          <p>
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or by
            emailing at support@harmonyapp.ai.
          </p>
          <div>
            <span>Usage Data</span>
            <div>
              <p>
                We may also collect information that your browser sends whenever
                you visit our Service or when you access Service by or through a
                mobile device ("<span>Usage Data</span>").
              </p>
              <p>
                This Usage Data may include information such as your computer's
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that you visit, the
                time and date of your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </p>
              <p>
                When you access Service with a mobile device, this Usage Data
                may include information such as the type of mobile device you
                use, your mobile device unique ID, the IP address of your mobile
                device, your mobile operating system, the type of mobile
                Internet browser you use, unique device identifiers and other
                diagnostic data.
              </p>
            </div>
          </div>
          <div>
            <span>Tracking Cookies Data</span>
            <div>
              <p>
                We use cookies and similar tracking technologies to track the
                activity on our Service and we hold certain information.
              </p>
              <p>
                Cookies are files with a small amount of data which may include
                an anonymous unique identifier. Cookies are sent to your browser
                from a website and stored on your device. Other tracking
                technologies are also used such as beacons, tags and scripts to
                collect and track information and to improve and analyze our
                Service.
              </p>
              <p>
                Cookies are files with a small amount of data which may include
                an anonymous unique identifier. Cookies are sent to your browser
                from a website and stored on your device. Other tracking
                technologies are also used such as beacons, tags and scripts to
                collect and track information and to improve and analyze our
                Service.
              </p>
              <p>
                You can instruct your browser to refuse all cookies or to
                indicate when a cookie is being sent. However, if you do not
                accept cookies, you may not be able to use some portions of our
                Service.
              </p>
              <p>Examples of Cookies we use:</p>
              <div>
                <p>
                  (a) <span>Session Cookies:</span> We use Session Cookies to
                  operate our Service.
                </p>
                <p>
                  (b) <span>Preference Cookies:</span> We use Preference Cookies
                  to remember your preferences and various settings.
                </p>
                <p>
                  (c) <span>Security Cookies:</span> We use Security Cookies for
                  security purposes.
                </p>
                <p>
                  (d) <span>Advertising Cookies:</span> Advertising Cookies are
                  used to serve you with advertisements that may be relevant to
                  you and your interests.
                </p>
              </div>
            </div>
          </div>
          <div>
            <span>Other Data</span>
            <p>
              While using our Service, we may also collect the following
              information: sex, age, date of birth, place of birth, passport
              details, citizenship, registration at place of residence and
              actual address, telephone number (work, mobile), details of
              documents on education, qualification, professional training,
              employment agreements, non-disclosure agreements, information on
              bonuses and compensation, information on marital status, family
              members, social security (or other taxpayer identification)
              number, office location and other data.
            </p>
          </div>
        </div>
      </div>
      <div>
        <p>5. Use of Data</p>
        <div>
          <p>
            Ditmar Hoxha, trading as Harmony, uses the collected data for
            various purposes:
          </p>
          <div className={classes.orders}>
            <p>
              <span>(a)</span> to provide and maintain our Service;
            </p>
            <p>
              <span>(b)</span> to notify you about changes to our Service;{' '}
            </p>
            <p>
              <span>(c)</span> to allow you to participate in interactive
              features of our Service when you choose to do so;
            </p>
            <p>
              <span>(d)</span> to provide customer support;
            </p>
            <p>
              <span>(e)</span> to gather analysis or valuable information so
              that we can improve our Service;
            </p>
            <p>
              <span>(f)</span> to monitor the usage of our Service;
            </p>
            <p>
              <span>(g)</span> to detect, prevent and address technical issues;
            </p>
            <p>
              <span>(h)</span> to fulfill any other purpose for which you
              provide it;
            </p>
            <p>
              <span>(i)</span> to carry out our obligations and enforce our
              rights arising from any contracts entered into between you and us,
              including for billing and collection;
            </p>
            <p>
              <span>(j)</span> to provide you with notices about your account
              and/or subscription, including expiration and renewal notices,
              email-instructions, etc.;
            </p>
            <p>
              <span>(k)</span> to provide you with news, special offers and
              general information about other goods, services and events which
              we offer that are similar to those that you have already purchased
              or enquired about unless you have opted not to receive such
              information;
            </p>
            <p>
              <span>(l)</span> in any other way we may describe when you provide
              the information;
            </p>
            <p>
              <span>(m)</span> In order to continually improve the accuracy and
              performance of our facial analysis technology, we reserve the
              right to use the photos and associated landmark data you upload
              through our Service. This data may be analyzed and incorporated
              into our AI model to enhance its precision and effectiveness. By
              using our Service, you grant us permission to use this data for
              the purposes of improving our technology. Please note that all
              data used for these purposes will be handled in accordance with
              our Privacy Policy, ensuring the protection of your personal
              information.
            </p>
            <p>
              <span>(n)</span> for any other purpose with your consent.
            </p>
          </div>
        </div>
      </div>
      <div>
        <p>6. Retention of Data</p>
        <div>
          <p>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </p>
          <p>
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this
            data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </p>
        </div>
      </div>
      <div>
        <p>7. Transfer of Data</p>
        <div>
          <p>
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </p>
          <p>
            If you are located outside United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to United States and process it there.
          </p>
          <p>
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </p>
          <p>
            Ditmar Hoxha, trading as Harmony, will take all the steps reasonably
            necessary to ensure that your data is treated securely and in
            accordance with this Privacy Policy and no transfer of your Personal
            Data will take place to an organization or a country unless there
            are adequate controls in place including the security of your data
            and other personal information.
          </p>
        </div>
      </div>
      <div>
        <p>8. Disclosure of Data</p>
        <div>
          <p>
            We may disclose personal information that we collect, or you
            provide:
          </p>
          <div>
            <div>
              <div>
                <p>
                  <span>(a) Disclosure for Law Enforcement.</span>
                </p>
                <p>
                  Under certain circumstances, we may be required to disclose
                  your Personal Data if required to do so by law or in response
                  to valid requests by public authorities.
                </p>
              </div>
              <div>
                <p>
                  <span>(b) Business Transaction.</span>
                </p>
                <p>
                  If we or our subsidiaries are involved in a merger,
                  acquisition or asset sale, your Personal Data may be
                  transferred.
                </p>
              </div>
              <div>
                <p>
                  <span>
                    (c) Other cases. We may disclose your information also:
                  </span>
                </p>
                <div className={classes.orders}>
                  <p>
                    <span>(i)</span> to our subsidiaries and affiliates;
                  </p>
                  <p>
                    <span>(ii)</span> to contractors, service providers, and
                    other third parties we use to support our business;
                  </p>
                  <p>
                    <span>(iii)</span> to fulfill the purpose for which you
                    provide it;
                  </p>
                  <p>
                    <span>(iv)</span> for the purpose of including your
                    company’s logo on our website;
                  </p>
                  <p>
                    <span>(v)</span> for any other purpose disclosed by us when
                    you provide the information;
                  </p>
                  <p>
                    <span>(vi)</span> with your consent in any other cases;
                  </p>
                  <p>
                    <span>(vii)</span> if we believe disclosure is necessary or
                    appropriate to protect the rights, property, or safety of
                    the Company, our customers, or others.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <p>9. Security of Data</p>
        <div>
          <p>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>
        </div>
      </div>
      <div>
        <p>
          10. Your Data Protection Rights Under General Data Protection
          Regulation (GDPR)
        </p>
        <div>
          <p>
            If you are a resident of the European Union (EU) and European
            Economic Area (EEA), you have certain data protection rights,
            covered by GDPR. – See more at{' '}
            <a
              href="https://eur-lex.europa.eu/eli/reg/2016/679/oj"
              target="_blank"
            >
              https://eur-lex.europa.eu/eli/reg/2016/679/oj
            </a>
          </p>
          <p>
            We aim to take reasonable steps to allow you to correct, amend,
            delete, or limit the use of your Personal Data.
          </p>
          <p>
            If you wish to be informed what Personal Data we hold about you and
            if you want it to be removed from our systems, please email us at
            support@harmonyapp.ai.
          </p>
          <p>
            In certain circumstances, you have the following data protection
            rights:
          </p>
          <div className={classes.orders}>
            <p>
              <span>(a)</span> the right to access, update or to delete the
              information we have on you;
            </p>
            <p>
              <span>(b)</span> the right of rectification. You have the right to
              have your information rectified if that information is inaccurate
              or incomplete;
            </p>
            <p>
              <span>(c)</span> the right to object. You have the right to object
              to our processing of your Personal Data;
            </p>
            <p>
              <span>(d)</span> the right of restriction. You have the right to
              request that we restrict the processing of your personal
              information;
            </p>
            <p>
              <span>(e)</span> the right to data portability. You have the right
              to be provided with a copy of your Personal Data in a structured,
              machine-readable and commonly used format;
            </p>
            <p>
              <span>(f)</span> the right to withdraw consent. You also have the
              right to withdraw your consent at any time where we rely on your
              consent to process your personal information;
            </p>
          </div>
          <p>
            Please note that we may ask you to verify your identity before
            responding to such requests. Please note, we may not be able to
            provide Service without some necessary data.
          </p>
          <p>
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </p>
        </div>
      </div>
      <div>
        <p>
          11. Your Data Protection Rights under the California Privacy
          Protection Act (CalOPPA)
        </p>
        <div>
          <p>
            CalOPPA is the first state law in the nation to require commercial
            websites and online services to post a privacy policy. The law’s
            reach stretches well beyond California to require a person or
            company in the United States (and conceivable the world) that
            operates websites collecting personally identifiable information
            from California consumers to post a conspicuous privacy policy on
            its website stating exactly the information being collected and
            those individuals with whom it is being shared, and to comply with
            this policy. – See more at:{' '}
            <a
              href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3"
              target="_blank"
            >
              https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3
            </a>
          </p>
          <p>According to CalOPPA we agree to the following:</p>
          <div className={classes.orders}>
            <p>
              <span>(a)</span> users can visit our site anonymously;
            </p>
            <p>
              <span>(b)</span> our Privacy Policy link includes the word
              "Privacy", and can easily be found on the page specified above on
              the home page of our website;
            </p>
            <p>
              <span>(c)</span> users will be notified of any privacy policy
              changes on our Privacy Policy Page;
            </p>
            <p>
              <span>(d)</span> users are able to change their personal
              information by emailing us at support@harmonyapp.ai.
            </p>
          </div>
          <p>Our Policy on "Do Not Track" Signals:</p>
          <p>
            We honor Do Not Track signals and do not track, plant cookies, or
            use advertising when a Do Not Track browser mechanism is in place.
            Do Not Track is a preference you can set in your web browser to
            inform websites that you do not want to be tracked.{' '}
          </p>
          <p>
            You can enable or disable Do Not Track by visiting the Preferences
            or Settings page of your web browser.
          </p>
        </div>
      </div>
      <div>
        <p>12. Service Providers</p>
        <div>
          <p>
            We may employ third party companies and individuals to facilitate
            our Service ("<span>Service Providers</span>"), provide Service on
            our behalf, perform Service-related services or assist us in
            analyzing how our Service is used.
          </p>
          <p>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>
        </div>
      </div>
      <div>
        <p>13. Analytics</p>
        <div>
          <p>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>
          <div>
            <p>
              <span>Google Analytics</span>
            </p>
            <div>
              <p>
                Google Analytics is a web analytics service offered by Google
                that tracks and reports website traffic. Google uses the data
                collected to track and monitor the use of our Service. This data
                is shared with other Google services. Google may use the
                collected data to contextualize and personalize the ads of its
                own advertising network.
              </p>
            </div>
          </div>
          <p>
            For more information on the privacy practices of Google, please
            visit the Google Privacy Terms web page:{' '}
            <a href="https://policies.google.com/privacy?hl=en" target="_blank">
              https://policies.google.com/privacy?hl=en
            </a>
          </p>
          <p>
            We also encourage you to review the Google's policy for safeguarding
            your data:{' '}
            <a
              href="https://support.google.com/analytics/answer/6004245"
              target="_blank"
            >
              https://support.google.com/analytics/answer/6004245
            </a>
            .
          </p>
        </div>
      </div>
      <div>
        <p>14. CI/CD tools</p>
        <div>
          <p>
            We may use third-party Service Providers to automate the development
            process of our Service.
          </p>
          <p>
            <span>GitHub</span>
          </p>
          <p>GitHub is provided by GitHub, Inc.</p>
          <p>
            GitHub is a development platform to host and review code, manage
            projects, and build software.
          </p>
          <p>
            For more information on what data GitHub collects for what purpose
            and how the protection of the data is ensured, please visit GitHub
            Privacy Policy page:{' '}
            <a
              href="https://help.github.com/en/articles/github-privacy-statement"
              target="_blank"
            >
              https://help.github.com/en/articles/github-privacy-statement
            </a>
            .
          </p>
        </div>
      </div>
      <div>
        <p>15. Behavioral Remarketing</p>
        <div>
          <p>
            Ditmar Hoxha, trading as Harmony, uses remarketing services to
            advertise on third party websites to you after you visited our
            Service. We and our third-party vendors use cookies to inform,
            optimize and serve ads based on your past visits to our Service.
          </p>
          <div>
            <p>
              <span>Google Ads (AdWords)</span>
            </p>
            <div>
              <p>
                Google Ads (AdWords) remarketing service is provided by Google
                Inc.
              </p>
            </div>
          </div>
          <p>
            You can opt-out of Google Analytics for Display Advertising and
            customize the Google Display Network ads by visiting the Google Ads
            Settings page:{' '}
            <a href="http://www.google.com/settings/ads" target="_blank">
              http://www.google.com/settings/ads
            </a>
          </p>
          <p>
            Google also recommends installing the Google Analytics Opt-out
            Browser Add-on –{' '}
            <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">
              https://tools.google.com/dlpage/gaoptout
            </a>{' '}
            – for your web browser. Google Analytics Opt-out Browser Add-on
            provides visitors with the ability to prevent their data from being
            collected and used by Google Analytics.
          </p>
          <p>
            For more information on the privacy practices of Google, please
            visit the Google Privacy Terms web page:{' '}
            <a href="https://policies.google.com/privacy?hl=en" target="_blank">
              https://policies.google.com/privacy?hl=en
            </a>
          </p>
        </div>
      </div>
      <div>
        <p>16. Payments</p>
        <div>
          <p>
            We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g.
            payment processors).
          </p>
          <p>
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processors whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
          </p>
          <p>The payment processors we work with are:</p>
          <div>
            <p>
              <span>PayPal or Braintree:</span>
            </p>
            <div>
              <p>
                Their Privacy Policy can be viewed at{' '}
                <a
                  href="https://www.paypal.com/webapps/mpp/ua/privacy-full"
                  target="_blank"
                >
                  https://www.paypal.com/webapps/mpp/ua/privacy-full
                </a>
              </p>
            </div>
          </div>
          <div>
            <p>
              <span>Stripe:</span>
            </p>
            <div>
              <p>
                Their Privacy Policy can be viewed at:{' '}
                <a href="https://stripe.com/us/privacy" target="_blank">
                  https://stripe.com/us/privacy
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div>
        <p>17. Links to Other Sites</p>
        <div>
          <p>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party's site. We strongly advise you to review the Privacy
            Policy of every site you visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </div>
      </div>
      <div>
        <p>18. Children's Privacy</p>
        <div>
          <p>
            Our Services are not intended for use by children under the age of
            13 ("<span>Children</span>").{' '}
          </p>
          <p>
            We do not knowingly collect personally identifiable information from
            Children under 13. If you become aware that a Child has provided us
            with Personal Data, please contact us. If we become aware that we
            have collected Personal Data from Children without verification of
            parental consent, we take steps to remove that information from our
            servers.
          </p>
        </div>
      </div>
      <div>
        <p>19. Changes to This Privacy Policy</p>
        <div>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>
          <p>
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update
            "effective date" at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </div>
      </div>
      <div>
        <p>20. Contact Us</p>
        <div>
          <p>
            If you have any questions about this Privacy Policy, please contact
            us:
          </p>
          <p>By email: support@harmonyapp.ai.</p>
        </div>
      </div>
    </div>
  );
}

function PrivatePolicyDialog({ open, onClose }: IPrivatePolicyDialogProps) {
  return (
    <Dialog
      open={open}
      onClose={onClose}
      header={<p className={classes.title}>Privacy Policy</p>}
      body={<PrivatePolicy />}
      maxWidth="screen"
    />
  );
}

export default PrivatePolicyDialog;
